version: "3.8"
services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASS: master123
      DB_NAME: cpfs
    command: npm run start

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend
    command: npm run dev

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: master123
      POSTGRES_DB: cpfs
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
