version: '3.8'
services:
  db:
    image: postgres:15
    container_name: postgres-cpfs
    environment:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: admin
      DB_PASS: master123
      DB_NAME: cpfs
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASS: master123
      DB_NAME: cpfs
    command: npm run start:dev

volumes:
  db_data:
# networks:
#   app-network:
#     driver: bridge
